@startuml hal

title Hardware Abstraction Layer (HAL)

package "HAL contracts" as contractsPkg {

    package "GPIO" as gpioPkg {
        class "DOutPin" as dOutPin
        class "DInPin" as dInPin
        class "AnalogPin" as analogPin
    }

    interface "IBoard" as iBoard
    interface "IDisplayDrv" as iDisplayDrv
    interface "IButtonDrv" as iButtonDrv
    interface "IBuzzerDrv" as iBuzzerDrv
    interface "ILedDrv" as iLedDrv
    interface "ISystemDrv" as iSystemDrv
    interface "ISensor" as iSensor
    interface "ISensorChannel" as iSensorChannel

    class "SensorChannelType<T>" as sensorChannelType
    sensorChannelType ..|> iSensorChannel
    iSensor --> iSensorChannel: <<provide>>
}

package "HAL implementations" as halPkg {

    class "Board" as board <<singleton>>
    class "ButtonDrv" as buttonDrv
    class "BuzzerDrv" as buzzerDrv
    class "LedDrv" as ledDrv
    class "SystemDrv" as systemDrv

    package "Selected display HAL" as displayHalPkg {
        class "DisplayDrv\n(HalLedMatrix)" as ledMatrixDisplayDrv
        class "DisplayDrv\n(HalHub75Esp32)" as hub75DisplayDrv
        class "DisplayDrv\n(HalTftDisplay)" as tftDisplayDrv
    }

    package "Sensors" as sensorsPkg {
        class "Sensors" as sensors <<namespace>>
        class "SensorBattery" as sensorBattery
        class "SensorDhtX" as sensorDhtX
        class "SensorLdr" as sensorLdr
        class "SensorSht3X" as sensorSht3X
    }

    note right of board
        A board owns the common ESP32 drivers and
        exactly one display driver selected at build time.
    end note

    board ..|> iBoard
    board *--> buttonDrv
    board *--> buzzerDrv
    board *--> ledDrv
    board *--> systemDrv
    board o--> "1" iDisplayDrv: selected driver

    buttonDrv ..|> iButtonDrv
    buzzerDrv ..|> iBuzzerDrv
    ledDrv ..|> iLedDrv
    systemDrv ..|> iSystemDrv
    ledMatrixDisplayDrv ..|> iDisplayDrv
    hub75DisplayDrv ..|> iDisplayDrv
    tftDisplayDrv ..|> iDisplayDrv

    buttonDrv --> dInPin
    buzzerDrv --> dOutPin
    ledDrv --> dOutPin
    sensorBattery --> analogPin
    sensorDhtX --> dInPin
    sensorLdr --> analogPin
    sensorSht3X --> dInPin

    sensors *--> sensorBattery
    sensors *--> sensorDhtX
    sensors *--> sensorLdr
    sensors *--> sensorSht3X
    sensorBattery ..|> iSensor
    sensorDhtX ..|> iSensor
    sensorLdr ..|> iSensor
    sensorSht3X ..|> iSensor
}

package "Application" as appPkg {
    class "Display" as display
    class "SensorDataProvider" as sensorDataProvider <<singleton>>
    class "Application services" as app
}

display ....> iDisplayDrv: <<use>>
app ....> iBoard: <<use>>
sensorDataProvider ...> sensors: <<use>>

@enduml