@startuml widgets

class YAGfx
class YAGfxCanvas

note left of YAGfxCanvas
    The widget uses the canvas to draw itself.
end note

class Widget {
    - m_canvas : YAGfxCanvas
    - {abstract} paint(gfx : YAGfx&) : void
    + update(gfx : YAGfx&) : void
}

note left of Widget
    The base widget provides the common widget functionality.
    It contains the width, height and position in the parent canvas.
end note

YAGfx <|-- YAGfxCanvas
YAGfxCanvas <-- Widget

class BitmapWidget {
    - paint(gfx : YAGfx&) : void
}
class CanvasWidget {
    - paint(gfx : YAGfx&) : void
}

class LampWidget {
    - paint(gfx : YAGfx&) : void
}

class ProgressBar {
    - paint(gfx : YAGfx&) : void
}

class TextWidget {
    - paint(gfx : YAGfx&) : void
}

Widget <|-- BitmapWidget
Widget <|-- CanvasWidget
Widget <|-- LampWidget
Widget <|-- ProgressBar
Widget <|-- TextWidget

@enduml