@startuml

title GFX

package "Makuna" {
    class "NeoPixelBrightnessBus" as neoPixelBrightnessBus

    note top of neoPixelBrightnessBus
        Using RMT to drive the physical LEDs.
    end note

    class "NeoTopology" as neoTopology

    note top of neoTopology
        Maps x,y coordinates to framebuffer index,
        depended on physical panel layout.
    end note
}

package "Adafruit" {
    class "Adafruit_GFX" as adafruitGfx

    note top of adafruitGfx
        Disadvantages:
        * Supports only 16 bit color (RGB565).
        * Needs SPI as header include.
    end note
}

class "LedMatrix" as ledMatrix

adafruitGfx <|.. ledMatrix: <<realize>>
neoPixelBrightnessBus <--* ledMatrix: <<contains>>
neoTopology <--* ledMatrix:: <<contains>>

note right of ledMatrix
    Represents the physical LED matrix and
    provides the GFX interface to draw inside.
end note

class "DisplayMgr" as displayMgr

ledMatrix <.. displayMgr: <<uses>>

note right of displayMgr
    Manages the logic layout, containing widgets.
    It provides a simple interface for the
    application.
end note

class "App" as app

displayMgr <.. app: <<uses>>

@enduml