@startuml

title Plugin Service

participant "App" as app
participant "PluginMgr" as pluginMgr
participant "DisplayMgr" as displayMgr
participant "Plugin" as plugin
participant "Webserver" as webServer

note over app,webServer
    Install plugin
end note

app -> pluginMgr: Install concrete plugin.
pluginMgr -> plugin: Create concrete plugin.
plugin --> pluginMgr: Concrete plugin
pluginMgr -> displayMgr: Install plugin in display slot.

alt Empty slot available
    displayMgr -> displayMgr: Add plugin to available slot.
    displayMgr -> plugin: Set slot interface.
    plugin --> displayMgr
    displayMgr -> plugin: Start plugin.
    plugin --> displayMgr
    displayMgr --> pluginMgr: slot id
    pluginMgr -> plugin: Get topics, used for web communication.
    plugin --> pluginMgr: List of topics

    loop for each topic
        pluginMgr -> plugin: Get topic parameters.
        plugin --> pluginMgr: Topic parameters
        pluginMgr -> webServer: Register web interface
        webServer --> pluginMgr: Web handler
    end loop

    pluginMgr --> app: Concrete plugin

    alt Depends on application
        app -> plugin: Enable plugin.
        plugin --> app
    end alt
else No slot available
    displayMgr --> pluginMgr: invalid slot id
    pluginMgr --> app: no plugin
end alt

note over app,webServer
    Uninstall plugin
end note

app -> pluginMgr: Uninstall concrete plugin.
pluginMgr -> displayMgr: Uninstall plugin.

loop for each web handler
    pluginMgr -> webServer: UnRegister web interface
    webServer --> pluginMgr
end loop

displayMgr -> plugin: Stop plugin.
plugin --> displayMgr
displayMgr -> displayMgr: Remove plugin from slot.
displayMgr -> plugin: Set invalid slot id.
plugin --> displayMgr
displayMgr --> pluginMgr
pluginMgr -> pluginMgr: Destroy concrete plugin.
pluginMgr --> app

note over app,webServer
    Plugin scheduler
end note

alt Plugin selected to show?

    displayMgr -> displayMgr: Set selected slot, retrieved from selected plugin.

    alt Selected plugin disabled in the meantime?
        displayMgr -> displayMgr: Stop plugin duration timer.
        displayMgr -> displayMgr: Clear selected plugin.
    end alt

end alt

alt No plugin selected?

    displayMgr -> displayMgr: Find next slot with installed and enabled plugin.

    alt Installed and enabled plugin found?
        displayMgr -> displayMgr: Select plugin.
        displayMgr -> plugin: Get how long slot shall be active.
        plugin --> displayMgr: duration

        alt Is duration not infinite?
            displayMgr -> displayMgr: Start plugin duration timer.
        end alt
    end alt

end alt

loop For all installed plugins

    alt Is plugin is enabled?

        displayMgr -> plugin: Process plugin.
        plugin --> displayMgr

    end alt

end loop

displayMgr -> displayMgr: Clear display

alt Is a plugin selected?
    displayMgr -> plugin: Call selected plugin to update framebuffer.
    plugin --> displayMgr
end alt

displayMgr -> displayMgr: Update display with framebuffer.

alt Is plugin duration timer active?
    alt Is plugin duration timer timeout?
        displayMgr -> displayMgr: Stop plugin run duration timer.
        displayMgr -> displayMgr: Clear selected plugin.
    end alt
end alt

@enduml