@startuml
title Startup

(*) --> "Initialize hardware"

--> "Check user button state"

if "Is pressed?" then
    --> [false] "Check SPIFFS for wifi credentials"
    if "Is available?" then
        --> [false] "Show instructions on matrix" 
        note top
            E.g. 
            "restart with pressed button"
        end note
        --> ===Failed===
    else
        --> [true] "Try to establish wifi connection"
        if "Connection successful established?" then
            --> [false] "Show error message on matrix" 
            note bottom
                E.g. 
                "unknown SSID/PW, reconfigure"
            end note
            --> ===Failed===
        else
            --> [true] ===Success===
        endif
    endif
else
    --> [true] "Setting up access-point (AP)"
    --> "Show SSID of AP on the matrix"
    note right
        E.g. connect to 
        "ESP-RGB-LED-MATRIX"
    end note
    --> ===Success===
endif

===Failed=== --> "Waiting for reboot"
--> (*)

===Success=== --> "Setting up tcp/ip server"
--> "Handle all kind of requests"
--> (*)

@enduml