@startuml
title Startup

start
:Initialize hardware;
:Check user button state;

if (Is pressed?) then (yes)

    :Check SPIFFS for wifi credentials;

    if (Is available?) then (yes)

        repeat
            :Show connection establishment on LED matrix.;
            :Try to establish wifi connection.;

            if (Wifi with SSID not found?) then (yes)
                :Show SSID not found on LED matrix.;
                :Wait 30 s.;
            else if (Password wrong?) then (yes)
                :Show invalid password on LED matrix.;
                stop
            else if (Any other error?) then (yes)
                :Show error on LED matrix.;
                stop
            else (no)
            endif

        repeat while(Connection successful established?)

    else (no)

        :Show instructions on matrix;
        note right
            E.g. 
            "restart with pressed button"
        end note

        :Wait for restart;
        stop

    endif

else

    :Setting up access-point (AP);
    :Show SSID of AP on the matrix;
    note right
        E.g. connect to 
        "ESP-RGB-LED-MATRIX"
    end note

endif

:Handle all kind of requests;
stop

@enduml