@startuml

title SW Deployment on ESP32

node "ESP32" {

    node "Core 0\n(Protocol CPU, PRO_CPU)" as proCpu {

        component "IDLE0\n(prio 0)" as idle1Task
        component "Tmr Svc\n(prio 1)" as tmrSvcTask
        component "mdns\n(prio 1)" as mdnsTask
        component "tiT\n(prio 18)\nLwIP TCP/IP task" as tiTTask
        component "eventTask\n(prio 20)" as eventTask
        component "esp_timer\n(prio 22)" as espTimerTask
        component "wifi\n(prio 23)" as wifiTask
        component "ipc0\n(prio 24)\nInter-Processor Call task" as ipc0Task
    }
    
    node "Core 1\n(Application CPU, APP_CPU)" as appCpu {
    
        component "IDLE1\n(prio 0)" as idle0Task
        component "loopTask\n(prio 1)" as loopTask
        component "buttonTask\n(prio 1)" as buttonTask
        component "async_tcp\n(prio 3)" as asyncTcpTask
        component "displayTask\n(prio 4)" as displayTask
        component "network_event\n(prio 19)" as networkEventTask
        component "ipc1\n(prio 24)\nInter-Processor Call task" as ipc1Task
    }

    note top of proCpu
        The CPU 0 controls the WLAN, Bluetooth and
        other internal peripherals such as SPI,
        I2C, ADC, etc.
    end note

    note top of appCpu
        The CPU 1 is available to our user program.
    end note
}

@enduml