@startuml

title SW Deployment on ESP32

node "ESP32" {

    node "Core 0\n(Protocol CPU, PRO_CPU)" as proCpu{
    }
    
    node "Core 1\n(Application CPU, APP_CPU)" as appCpu {
    
        component "Task Button\n(prio 1)" as taskButton
        component "Task Arduino\n(loopTask, prio 1)" as taskArduino
        component "Task Webserver\n(prio 3)" as taskWebServer
        component "OS\n(FreeRTOS)" as os
    
        taskArduino <-- os: <<calls>>
        taskButton <-- os: <<calls>>
        taskWebServer <-- os: <<calls>>
    }

    note top of proCpu
        The CPU 0 controls the WLAN, Bluetooth and
        other internal peripherals such as SPI,
        I2C, ADC, etc.
    end note

    note top of appCpu
        The CPU 1 is available to our user program.
    end note
}

@enduml