@startuml

title ESP-RGB-LED Matrix

component "Power Supply" as powerSupply

package "Housing" {

    package "PCB" as pcb {
        component "Overcurrent protection" as ocp
        component "Inverse connection protection" as icp
        component "Overvoltage protection" as ovp
        
        package "ESP32 DevKitV1 connector" {
        
            component "ESP32 DevKitV1" as esp32s
        }
    }
    
    component "LED matrix" as ledMatrix
    component "Button" as button
    component "Ambilight sensor" as ambilightSensor
}

powerSupply -- ocp: Vcc (5 V / 4 A)
ocp -- icp
icp -- ovp
ovp -r- esp32s: Vcc_protected
ovp -- ledMatrix: Vcc_protected

esp32s -- ledMatrix: data
esp32s -- button: input
esp32s -- ambilightSensor

@enduml