@startuml

title System State Machine

InitState: /entry: Initialize HAL and slot layouts.
InitState: /do: Get button state.

APState: /entry: Setup access point.
APState: /do: Handle client requests.
APState: /do: Handle update.

IdleState: /do: Wait for manual reset.

ConnectingState: /entry: Get remote wifi SSID and passphrase.
ConnectingState: /do: Connect every 30 s to remote wifi network.

ConnectedState: /entry: Show hostname.
ConnectedState: /entry: Enable slot routing on the display.
ConnectedState: /do: Handle client requests.
ConnectedState: /do: Handle update.

ErrorState: /do: Wait for manual reset.

[*] --> InitState: Power up
InitState --> APState: [Button pressed]
InitState -> ConnectingState: [Button released]
APState --> [*]: [Restart]
APState --> ErrorState: [Failed to start\nwifi access point]
ConnectingState --> IdleState: [Remote wifi SSID or\npassword missing]
ConnectingState --> ConnectedState: [Connection successful established]
ConnectedState --> ConnectingState: [Connection lost]
ErrorState --> [*]: [Restart]
IdleState --> [*]: [Restart]

@enduml