@startuml MakapixPlugin

class "PluginWithConfig" as pluginWithConfig

package "MakapixPlugin" {
    class "MakapixPlugin" as makapixPlugin
    class "ArtworkDownloader" as artworkDownloader
    class "Channel" as channel
    class "Playlist" as playlist
    class "CommandHandler" as commandHandler
    class "RequestHandler" as requestHandler
    class "MqttTopic" as mqttTopic<<module>>
}

package "Services" {
    class "HttpService" as httpService<<singleton>>
    class "MqttService" as mqttService<<singleton>>
}

pluginWithConfig <|.. makapixPlugin: <<realize>>
makapixPlugin --> artworkDownloader
makapixPlugin --> channel
makapixPlugin ---> playlist
makapixPlugin --> commandHandler

artworkDownloader .....> httpService: <<uses>>

channel --> requestHandler
channel ..> playlist: <<uses>>

commandHandler .....> mqttService: <<uses>>
commandHandler ...> mqttTopic: <<uses>>
commandHandler ..> playlist: <<uses>>

requestHandler ....> mqttService: <<uses>>
requestHandler ..> mqttTopic: <<uses>>

@enduml
